/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const AbMinusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type AbMinusAf7Enum = typeof AbMinusAf7Enum[keyof typeof AbMinusAf7Enum];


export function AbMinusAf7EnumFromJSON(json: any): AbMinusAf7Enum {
    return AbMinusAf7EnumFromJSONTyped(json, false);
}

export function AbMinusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbMinusAf7Enum {
    return json as AbMinusAf7Enum;
}

export function AbMinusAf7EnumToJSON(value?: AbMinusAf7Enum | null): any {
    return value as any;
}

