/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const AbPlusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type AbPlusAf7Enum = typeof AbPlusAf7Enum[keyof typeof AbPlusAf7Enum];


export function AbPlusAf7EnumFromJSON(json: any): AbPlusAf7Enum {
    return AbPlusAf7EnumFromJSONTyped(json, false);
}

export function AbPlusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbPlusAf7Enum {
    return json as AbPlusAf7Enum;
}

export function AbPlusAf7EnumToJSON(value?: AbPlusAf7Enum | null): any {
    return value as any;
}

