/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { NullEnum } from './NullEnum';
import {
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import type { Status2e6Enum } from './Status2e6Enum';
import {
    Status2e6EnumFromJSON,
    Status2e6EnumFromJSONTyped,
    Status2e6EnumToJSON,
} from './Status2e6Enum';

/**
 * @type AddressNeedStatus
 * 
 * @export
 */
export type AddressNeedStatus = BlankEnum | NullEnum | Status2e6Enum;

export function AddressNeedStatusFromJSON(json: any): AddressNeedStatus {
    return AddressNeedStatusFromJSONTyped(json, false);
}

export function AddressNeedStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressNeedStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { test: 'test' } as any;
}

export function AddressNeedStatusToJSON(value?: AddressNeedStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return value;
}

