/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * * `unknown` - нет данных
 * @export
 */
export const AMinusC07Enum = {
    Need: 'need',
    NoNeed: 'no_need',
    Unknown: 'unknown'
} as const;
export type AMinusC07Enum = typeof AMinusC07Enum[keyof typeof AMinusC07Enum];


export function AMinusC07EnumFromJSON(json: any): AMinusC07Enum {
    return AMinusC07EnumFromJSONTyped(json, false);
}

export function AMinusC07EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AMinusC07Enum {
    return json as AMinusC07Enum;
}

export function AMinusC07EnumToJSON(value?: AMinusC07Enum | null): any {
    return value as any;
}

