/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const AMinusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type AMinusAf7Enum = typeof AMinusAf7Enum[keyof typeof AMinusAf7Enum];


export function AMinusAf7EnumFromJSON(json: any): AMinusAf7Enum {
    return AMinusAf7EnumFromJSONTyped(json, false);
}

export function AMinusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AMinusAf7Enum {
    return json as AMinusAf7Enum;
}

export function AMinusAf7EnumToJSON(value?: AMinusAf7Enum | null): any {
    return value as any;
}

