/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRecoverCreateRequest
 */
export interface AuthRecoverCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRecoverCreateRequest
     */
    username: string;
}

/**
 * Check if a given object implements the AuthRecoverCreateRequest interface.
 */
export function instanceOfAuthRecoverCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function AuthRecoverCreateRequestFromJSON(json: any): AuthRecoverCreateRequest {
    return AuthRecoverCreateRequestFromJSONTyped(json, false);
}

export function AuthRecoverCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRecoverCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function AuthRecoverCreateRequestToJSON(value?: AuthRecoverCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

