/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCheckSmsCodeCreate200Response
 */
export interface AuthCheckSmsCodeCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthCheckSmsCodeCreate200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthCheckSmsCodeCreate200Response interface.
 */
export function instanceOfAuthCheckSmsCodeCreate200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthCheckSmsCodeCreate200ResponseFromJSON(json: any): AuthCheckSmsCodeCreate200Response {
    return AuthCheckSmsCodeCreate200ResponseFromJSONTyped(json, false);
}

export function AuthCheckSmsCodeCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCheckSmsCodeCreate200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function AuthCheckSmsCodeCreate200ResponseToJSON(value?: AuthCheckSmsCodeCreate200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

