/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRecoverCreate200Response
 */
export interface AuthRecoverCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthRecoverCreate200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRecoverCreate200Response
     */
    loginType?: string;
}

/**
 * Check if a given object implements the AuthRecoverCreate200Response interface.
 */
export function instanceOfAuthRecoverCreate200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthRecoverCreate200ResponseFromJSON(json: any): AuthRecoverCreate200Response {
    return AuthRecoverCreate200ResponseFromJSONTyped(json, false);
}

export function AuthRecoverCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRecoverCreate200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'loginType': !exists(json, 'login_type') ? undefined : json['login_type'],
    };
}

export function AuthRecoverCreate200ResponseToJSON(value?: AuthRecoverCreate200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'login_type': value.loginType,
    };
}

