/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRecoverCreate400Response
 */
export interface AuthRecoverCreate400Response {
    /**
     * 
     * @type {string}
     * @memberof AuthRecoverCreate400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthRecoverCreate400Response interface.
 */
export function instanceOfAuthRecoverCreate400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthRecoverCreate400ResponseFromJSON(json: any): AuthRecoverCreate400Response {
    return AuthRecoverCreate400ResponseFromJSONTyped(json, false);
}

export function AuthRecoverCreate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRecoverCreate400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AuthRecoverCreate400ResponseToJSON(value?: AuthRecoverCreate400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

