/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCheckSmsCodeCreateRequest
 */
export interface AuthCheckSmsCodeCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthCheckSmsCodeCreateRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AuthCheckSmsCodeCreateRequest interface.
 */
export function instanceOfAuthCheckSmsCodeCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function AuthCheckSmsCodeCreateRequestFromJSON(json: any): AuthCheckSmsCodeCreateRequest {
    return AuthCheckSmsCodeCreateRequestFromJSONTyped(json, false);
}

export function AuthCheckSmsCodeCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCheckSmsCodeCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthCheckSmsCodeCreateRequestToJSON(value?: AuthCheckSmsCodeCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

