/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlankEnum = {
    Male: 'male',
    Female: 'female'
} as const;
export type BlankEnum = typeof BlankEnum[keyof typeof BlankEnum];


export function BlankEnumFromJSON(json: any): BlankEnum {
    return BlankEnumFromJSONTyped(json, false);
}

export function BlankEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlankEnum {
    return json as BlankEnum;
}

export function BlankEnumToJSON(value?: BlankEnum | null): any {
    return value as any;
}

