/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { BloodStationSmallBloodGroup } from './BloodStationSmallBloodGroup';
import {
    BloodStationSmallBloodGroupFromJSON,
    BloodStationSmallBloodGroupFromJSONTyped,
    BloodStationSmallBloodGroupToJSON,
} from './BloodStationSmallBloodGroup';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
} from './City';

/**
 * 
 * @export
 * @interface BloodStationSmall
 */
export interface BloodStationSmall {
    /**
     * 
     * @type {number}
     * @memberof BloodStationSmall
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof BloodStationSmall
     */
    cityId: number;
    /**
     * 
     * @type {City}
     * @memberof BloodStationSmall
     */
    city: City;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    readonly lat: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    readonly lng: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    title: string;
    /**
     * 
     * @type {BloodStationSmallBloodGroup}
     * @memberof BloodStationSmall
     */
    bloodGroup?: BloodStationSmallBloodGroup;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    parserUrl?: string | null;
    /**
     * Данные будут обновляться каждый день в час ночи.
     * @type {boolean}
     * @memberof BloodStationSmall
     */
    isGetFromParser?: boolean;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    oPlus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    oMinus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    aPlus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    aMinus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    bPlus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    bMinus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    abPlus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    abMinus?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    blood?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    plasma?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    platelets?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    erythrocytes?: BlankEnum;
    /**
     * 
     * @type {BlankEnum}
     * @memberof BloodStationSmall
     */
    leukocytes?: BlankEnum;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    site?: string;
    /**
     * Устаревшее поле
     * @type {string}
     * @memberof BloodStationSmall
     */
    phones?: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationSmall
     */
    email?: string;
    /**
     * Устаревшее поле
     * @type {string}
     * @memberof BloodStationSmall
     */
    worktime?: string;
    /**
     * Центры крови принимает доноров без местной прописки
     * @type {boolean}
     * @memberof BloodStationSmall
     */
    withoutRegistration?: boolean;
    /**
     * Здесь вы можете войти в <a href="https://wmdd2020.donorsearch.org" target="_blank">регистр доноров костного мозга</a>
     * @type {boolean}
     * @memberof BloodStationSmall
     */
    withTyping?: boolean;
    /**
     * Сдавая в этом центре крови можно получить звание Почётного донора Москвы
     * @type {boolean}
     * @memberof BloodStationSmall
     */
    forMoscow?: boolean;
    /**
     * Если данный центр крови больше не существует, то не будет показан в поиске, где сдать кровь. Однако при добавлении донаций, доноры могут найти этот центр крови, чтобы отметить свои старые донации.
     * @type {boolean}
     * @memberof BloodStationSmall
     */
    closed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BloodStationSmall
     */
    priority?: number;
}

/**
 * Check if a given object implements the BloodStationSmall interface.
 */
export function instanceOfBloodStationSmall(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "cityId" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "lat" in value;
    isInstance = isInstance && "lng" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function BloodStationSmallFromJSON(json: any): BloodStationSmall {
    return BloodStationSmallFromJSONTyped(json, false);
}

export function BloodStationSmallFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodStationSmall {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cityId': json['city_id'],
        'city': CityFromJSON(json['city']),
        'lat': json['lat'],
        'lng': json['lng'],
        'title': json['title'],
        'bloodGroup': !exists(json, 'blood_group') ? undefined : BloodStationSmallBloodGroupFromJSON(json['blood_group']),
        'parserUrl': !exists(json, 'parser_url') ? undefined : json['parser_url'],
        'isGetFromParser': !exists(json, 'is_get_from_parser') ? undefined : json['is_get_from_parser'],
        'oPlus': !exists(json, 'o_plus') ? undefined : BlankEnumFromJSON(json['o_plus']),
        'oMinus': !exists(json, 'o_minus') ? undefined : BlankEnumFromJSON(json['o_minus']),
        'aPlus': !exists(json, 'a_plus') ? undefined : BlankEnumFromJSON(json['a_plus']),
        'aMinus': !exists(json, 'a_minus') ? undefined : BlankEnumFromJSON(json['a_minus']),
        'bPlus': !exists(json, 'b_plus') ? undefined : BlankEnumFromJSON(json['b_plus']),
        'bMinus': !exists(json, 'b_minus') ? undefined : BlankEnumFromJSON(json['b_minus']),
        'abPlus': !exists(json, 'ab_plus') ? undefined : BlankEnumFromJSON(json['ab_plus']),
        'abMinus': !exists(json, 'ab_minus') ? undefined : BlankEnumFromJSON(json['ab_minus']),
        'blood': !exists(json, 'blood') ? undefined : BlankEnumFromJSON(json['blood']),
        'plasma': !exists(json, 'plasma') ? undefined : BlankEnumFromJSON(json['plasma']),
        'platelets': !exists(json, 'platelets') ? undefined : BlankEnumFromJSON(json['platelets']),
        'erythrocytes': !exists(json, 'erythrocytes') ? undefined : BlankEnumFromJSON(json['erythrocytes']),
        'leukocytes': !exists(json, 'leukocytes') ? undefined : BlankEnumFromJSON(json['leukocytes']),
        'address': !exists(json, 'address') ? undefined : json['address'],
        'site': !exists(json, 'site') ? undefined : json['site'],
        'phones': !exists(json, 'phones') ? undefined : json['phones'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'worktime': !exists(json, 'worktime') ? undefined : json['worktime'],
        'withoutRegistration': !exists(json, 'without_registration') ? undefined : json['without_registration'],
        'withTyping': !exists(json, 'with_typing') ? undefined : json['with_typing'],
        'forMoscow': !exists(json, 'for_moscow') ? undefined : json['for_moscow'],
        'closed': !exists(json, 'closed') ? undefined : json['closed'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
    };
}

export function BloodStationSmallToJSON(value?: BloodStationSmall | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'city_id': value.cityId,
        'city': CityToJSON(value.city),
        'title': value.title,
        'blood_group': BloodStationSmallBloodGroupToJSON(value.bloodGroup),
        'parser_url': value.parserUrl,
        'is_get_from_parser': value.isGetFromParser,
        'o_plus': BlankEnumToJSON(value.oPlus),
        'o_minus': BlankEnumToJSON(value.oMinus),
        'a_plus': BlankEnumToJSON(value.aPlus),
        'a_minus': BlankEnumToJSON(value.aMinus),
        'b_plus': BlankEnumToJSON(value.bPlus),
        'b_minus': BlankEnumToJSON(value.bMinus),
        'ab_plus': BlankEnumToJSON(value.abPlus),
        'ab_minus': BlankEnumToJSON(value.abMinus),
        'blood': BlankEnumToJSON(value.blood),
        'plasma': BlankEnumToJSON(value.plasma),
        'platelets': BlankEnumToJSON(value.platelets),
        'erythrocytes': BlankEnumToJSON(value.erythrocytes),
        'leukocytes': BlankEnumToJSON(value.leukocytes),
        'address': value.address,
        'site': value.site,
        'phones': value.phones,
        'email': value.email,
        'worktime': value.worktime,
        'without_registration': value.withoutRegistration,
        'with_typing': value.withTyping,
        'for_moscow': value.forMoscow,
        'closed': value.closed,
        'priority': value.priority,
    };
}

