/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { BloodStationSmallBloodGroupEnum } from './BloodStationSmallBloodGroupEnum';
import {
    BloodStationSmallBloodGroupEnumFromJSON,
    BloodStationSmallBloodGroupEnumFromJSONTyped,
    BloodStationSmallBloodGroupEnumToJSON,
} from './BloodStationSmallBloodGroupEnum';

/**
 * @type BloodStationSmallBloodGroup
 * 
 * @export
 */
export type BloodStationSmallBloodGroup = BlankEnum | BloodStationSmallBloodGroupEnum;

export function BloodStationSmallBloodGroupFromJSON(json: any): BloodStationSmallBloodGroup {
    return BloodStationSmallBloodGroupFromJSONTyped(json, false);
}

export function BloodStationSmallBloodGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodStationSmallBloodGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json;
}

export function BloodStationSmallBloodGroupToJSON(value?: BloodStationSmallBloodGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return value;
}

