/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `blood` - Цельная кровь
 * * `plasma` - Плазма
 * * `platelets` - Тромбоциты
 * * `erythrocytes` - Эритроциты
 * * `leukocytes` - Гранулоциты (Лейкоциты)
 * @export
 */
export const BloodClassF07Enum = {
    Blood: 'blood',
    Plasma: 'plasma',
    Platelets: 'platelets',
    Erythrocytes: 'erythrocytes',
    Leukocytes: 'leukocytes'
} as const;
export type BloodClassF07Enum = typeof BloodClassF07Enum[keyof typeof BloodClassF07Enum];


export function BloodClassF07EnumFromJSON(json: any): BloodClassF07Enum {
    return BloodClassF07EnumFromJSONTyped(json, false);
}

export function BloodClassF07EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodClassF07Enum {
    return json as BloodClassF07Enum;
}

export function BloodClassF07EnumToJSON(value?: BloodClassF07Enum | null): any {
    return value as any;
}

