/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `o_plus` - O(I) Rh+
 * * `o_minus` - O(I) Rh-
 * * `a_plus` - A(II) Rh+
 * * `a_minus` - A(II) Rh-
 * * `b_plus` - B(III) Rh+
 * * `b_minus` - B(III) Rh-
 * * `ab_plus` - AB(IV) Rh+
 * * `ab_minus` - AB(IV) Rh-
 * @export
 */
export const BloodStationSmallBloodGroupEnum = {
    OPlus: 'o_plus',
    OMinus: 'o_minus',
    APlus: 'a_plus',
    AMinus: 'a_minus',
    BPlus: 'b_plus',
    BMinus: 'b_minus',
    AbPlus: 'ab_plus',
    AbMinus: 'ab_minus'
} as const;
export type BloodStationSmallBloodGroupEnum = typeof BloodStationSmallBloodGroupEnum[keyof typeof BloodStationSmallBloodGroupEnum];


export function BloodStationSmallBloodGroupEnumFromJSON(json: any): BloodStationSmallBloodGroupEnum {
    return BloodStationSmallBloodGroupEnumFromJSONTyped(json, false);
}

export function BloodStationSmallBloodGroupEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodStationSmallBloodGroupEnum {
    return json as BloodStationSmallBloodGroupEnum;
}

export function BloodStationSmallBloodGroupEnumToJSON(value?: BloodStationSmallBloodGroupEnum | null): any {
    return value as any;
}

