/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `blood` - Цельная кровь
 * * `plasma` - Плазма
 * * `platelets` - Тромбоциты
 * * `erythrocytes` - Эритроциты
 * * `leukocytes` - Гранулоциты (Лейкоциты)
 * * `any` - Любой
 * @export
 */
export const BloodClass2c1Enum = {
    Blood: 'blood',
    Plasma: 'plasma',
    Platelets: 'platelets',
    Erythrocytes: 'erythrocytes',
    Leukocytes: 'leukocytes',
    Any: 'any'
} as const;
export type BloodClass2c1Enum = typeof BloodClass2c1Enum[keyof typeof BloodClass2c1Enum];


export function BloodClass2c1EnumFromJSON(json: any): BloodClass2c1Enum {
    return BloodClass2c1EnumFromJSONTyped(json, false);
}

export function BloodClass2c1EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodClass2c1Enum {
    return json as BloodClass2c1Enum;
}

export function BloodClass2c1EnumToJSON(value?: BloodClass2c1Enum | null): any {
    return value as any;
}

