/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AMinusC07Enum } from './AMinusC07Enum';
import {
    AMinusC07EnumFromJSON,
    AMinusC07EnumFromJSONTyped,
    AMinusC07EnumToJSON,
} from './AMinusC07Enum';
import type { APlusC07Enum } from './APlusC07Enum';
import {
    APlusC07EnumFromJSON,
    APlusC07EnumFromJSONTyped,
    APlusC07EnumToJSON,
} from './APlusC07Enum';
import type { AbMinusC07Enum } from './AbMinusC07Enum';
import {
    AbMinusC07EnumFromJSON,
    AbMinusC07EnumFromJSONTyped,
    AbMinusC07EnumToJSON,
} from './AbMinusC07Enum';
import type { AbPlusC07Enum } from './AbPlusC07Enum';
import {
    AbPlusC07EnumFromJSON,
    AbPlusC07EnumFromJSONTyped,
    AbPlusC07EnumToJSON,
} from './AbPlusC07Enum';
import type { BMinusC07Enum } from './BMinusC07Enum';
import {
    BMinusC07EnumFromJSON,
    BMinusC07EnumFromJSONTyped,
    BMinusC07EnumToJSON,
} from './BMinusC07Enum';
import type { BPlusC07Enum } from './BPlusC07Enum';
import {
    BPlusC07EnumFromJSON,
    BPlusC07EnumFromJSONTyped,
    BPlusC07EnumToJSON,
} from './BPlusC07Enum';
import type { BloodStationPhone } from './BloodStationPhone';
import {
    BloodStationPhoneFromJSON,
    BloodStationPhoneFromJSONTyped,
    BloodStationPhoneToJSON,
} from './BloodStationPhone';
import type { BloodStationSchedule } from './BloodStationSchedule';
import {
    BloodStationScheduleFromJSON,
    BloodStationScheduleFromJSONTyped,
    BloodStationScheduleToJSON,
} from './BloodStationSchedule';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
} from './City';
import type { LeukocytesEnum } from './LeukocytesEnum';
import {
    LeukocytesEnumFromJSON,
    LeukocytesEnumFromJSONTyped,
    LeukocytesEnumToJSON,
} from './LeukocytesEnum';
import type { OMinusC07Enum } from './OMinusC07Enum';
import {
    OMinusC07EnumFromJSON,
    OMinusC07EnumFromJSONTyped,
    OMinusC07EnumToJSON,
} from './OMinusC07Enum';
import type { OPlusC07Enum } from './OPlusC07Enum';
import {
    OPlusC07EnumFromJSON,
    OPlusC07EnumFromJSONTyped,
    OPlusC07EnumToJSON,
} from './OPlusC07Enum';

/**
 * 
 * @export
 * @interface BloodStationWithNeeds
 */
export interface BloodStationWithNeeds {
    /**
     * 
     * @type {number}
     * @memberof BloodStationWithNeeds
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof BloodStationWithNeeds
     */
    cityId: number;
    /**
     * 
     * @type {City}
     * @memberof BloodStationWithNeeds
     */
    city: City;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    readonly hasBloodGroup: string;
    /**
     * 
     * @type {Array<BloodStationSchedule>}
     * @memberof BloodStationWithNeeds
     */
    schedule: Array<BloodStationSchedule>;
    /**
     * 
     * @type {Array<BloodStationPhone>}
     * @memberof BloodStationWithNeeds
     */
    phoneNumbers: Array<BloodStationPhone>;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    readonly lat: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    readonly lng: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    readonly bloodGroup: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    readonly bloodStatus: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    parserUrl?: string | null;
    /**
     * Данные будут обновляться каждый день в час ночи.
     * @type {boolean}
     * @memberof BloodStationWithNeeds
     */
    isGetFromParser?: boolean;
    /**
     * 
     * @type {OPlusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    oPlus?: OPlusC07Enum;
    /**
     * 
     * @type {OMinusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    oMinus?: OMinusC07Enum;
    /**
     * 
     * @type {APlusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    aPlus?: APlusC07Enum;
    /**
     * 
     * @type {AMinusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    aMinus?: AMinusC07Enum;
    /**
     * 
     * @type {BPlusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    bPlus?: BPlusC07Enum;
    /**
     * 
     * @type {BMinusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    bMinus?: BMinusC07Enum;
    /**
     * 
     * @type {AbPlusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    abPlus?: AbPlusC07Enum;
    /**
     * 
     * @type {AbMinusC07Enum}
     * @memberof BloodStationWithNeeds
     */
    abMinus?: AbMinusC07Enum;
    /**
     * 
     * @type {LeukocytesEnum}
     * @memberof BloodStationWithNeeds
     */
    blood?: LeukocytesEnum;
    /**
     * 
     * @type {LeukocytesEnum}
     * @memberof BloodStationWithNeeds
     */
    plasma?: LeukocytesEnum;
    /**
     * 
     * @type {LeukocytesEnum}
     * @memberof BloodStationWithNeeds
     */
    platelets?: LeukocytesEnum;
    /**
     * 
     * @type {LeukocytesEnum}
     * @memberof BloodStationWithNeeds
     */
    erythrocytes?: LeukocytesEnum;
    /**
     * 
     * @type {LeukocytesEnum}
     * @memberof BloodStationWithNeeds
     */
    leukocytes?: LeukocytesEnum;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    site?: string;
    /**
     * Устаревшее поле
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    phones?: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    email?: string;
    /**
     * Устаревшее поле
     * @type {string}
     * @memberof BloodStationWithNeeds
     */
    worktime?: string;
    /**
     * Центры крови принимает доноров без местной прописки
     * @type {boolean}
     * @memberof BloodStationWithNeeds
     */
    withoutRegistration?: boolean;
    /**
     * Здесь вы можете войти в <a href="https://wmdd2020.donorsearch.org" target="_blank">регистр доноров костного мозга</a>
     * @type {boolean}
     * @memberof BloodStationWithNeeds
     */
    withTyping?: boolean;
    /**
     * Сдавая в этом центре крови можно получить звание Почётного донора Москвы
     * @type {boolean}
     * @memberof BloodStationWithNeeds
     */
    forMoscow?: boolean;
    /**
     * Если данный центр крови больше не существует, то не будет показан в поиске, где сдать кровь. Однако при добавлении донаций, доноры могут найти этот центр крови, чтобы отметить свои старые донации.
     * @type {boolean}
     * @memberof BloodStationWithNeeds
     */
    closed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BloodStationWithNeeds
     */
    priority?: number;
}

/**
 * Check if a given object implements the BloodStationWithNeeds interface.
 */
export function instanceOfBloodStationWithNeeds(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "cityId" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "hasBloodGroup" in value;
    isInstance = isInstance && "schedule" in value;
    isInstance = isInstance && "phoneNumbers" in value;
    isInstance = isInstance && "lat" in value;
    isInstance = isInstance && "lng" in value;
    isInstance = isInstance && "bloodGroup" in value;
    isInstance = isInstance && "bloodStatus" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function BloodStationWithNeedsFromJSON(json: any): BloodStationWithNeeds {
    return BloodStationWithNeedsFromJSONTyped(json, false);
}

export function BloodStationWithNeedsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodStationWithNeeds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cityId': json['city_id'],
        'city': CityFromJSON(json['city']),
        'hasBloodGroup': json['has_blood_group'],
        'schedule': ((json['schedule'] as Array<any>).map(BloodStationScheduleFromJSON)),
        'phoneNumbers': ((json['phone_numbers'] as Array<any>).map(BloodStationPhoneFromJSON)),
        'lat': json['lat'],
        'lng': json['lng'],
        'bloodGroup': json['blood_group'],
        'bloodStatus': json['blood_status'],
        'title': json['title'],
        'parserUrl': !exists(json, 'parser_url') ? undefined : json['parser_url'],
        'isGetFromParser': !exists(json, 'is_get_from_parser') ? undefined : json['is_get_from_parser'],
        'oPlus': !exists(json, 'o_plus') ? undefined : OPlusC07EnumFromJSON(json['o_plus']),
        'oMinus': !exists(json, 'o_minus') ? undefined : OMinusC07EnumFromJSON(json['o_minus']),
        'aPlus': !exists(json, 'a_plus') ? undefined : APlusC07EnumFromJSON(json['a_plus']),
        'aMinus': !exists(json, 'a_minus') ? undefined : AMinusC07EnumFromJSON(json['a_minus']),
        'bPlus': !exists(json, 'b_plus') ? undefined : BPlusC07EnumFromJSON(json['b_plus']),
        'bMinus': !exists(json, 'b_minus') ? undefined : BMinusC07EnumFromJSON(json['b_minus']),
        'abPlus': !exists(json, 'ab_plus') ? undefined : AbPlusC07EnumFromJSON(json['ab_plus']),
        'abMinus': !exists(json, 'ab_minus') ? undefined : AbMinusC07EnumFromJSON(json['ab_minus']),
        'blood': !exists(json, 'blood') ? undefined : LeukocytesEnumFromJSON(json['blood']),
        'plasma': !exists(json, 'plasma') ? undefined : LeukocytesEnumFromJSON(json['plasma']),
        'platelets': !exists(json, 'platelets') ? undefined : LeukocytesEnumFromJSON(json['platelets']),
        'erythrocytes': !exists(json, 'erythrocytes') ? undefined : LeukocytesEnumFromJSON(json['erythrocytes']),
        'leukocytes': !exists(json, 'leukocytes') ? undefined : LeukocytesEnumFromJSON(json['leukocytes']),
        'address': !exists(json, 'address') ? undefined : json['address'],
        'site': !exists(json, 'site') ? undefined : json['site'],
        'phones': !exists(json, 'phones') ? undefined : json['phones'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'worktime': !exists(json, 'worktime') ? undefined : json['worktime'],
        'withoutRegistration': !exists(json, 'without_registration') ? undefined : json['without_registration'],
        'withTyping': !exists(json, 'with_typing') ? undefined : json['with_typing'],
        'forMoscow': !exists(json, 'for_moscow') ? undefined : json['for_moscow'],
        'closed': !exists(json, 'closed') ? undefined : json['closed'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
    };
}

export function BloodStationWithNeedsToJSON(value?: BloodStationWithNeeds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'city_id': value.cityId,
        'city': CityToJSON(value.city),
        'schedule': ((value.schedule as Array<any>).map(BloodStationScheduleToJSON)),
        'phone_numbers': ((value.phoneNumbers as Array<any>).map(BloodStationPhoneToJSON)),
        'title': value.title,
        'parser_url': value.parserUrl,
        'is_get_from_parser': value.isGetFromParser,
        'o_plus': OPlusC07EnumToJSON(value.oPlus),
        'o_minus': OMinusC07EnumToJSON(value.oMinus),
        'a_plus': APlusC07EnumToJSON(value.aPlus),
        'a_minus': AMinusC07EnumToJSON(value.aMinus),
        'b_plus': BPlusC07EnumToJSON(value.bPlus),
        'b_minus': BMinusC07EnumToJSON(value.bMinus),
        'ab_plus': AbPlusC07EnumToJSON(value.abPlus),
        'ab_minus': AbMinusC07EnumToJSON(value.abMinus),
        'blood': LeukocytesEnumToJSON(value.blood),
        'plasma': LeukocytesEnumToJSON(value.plasma),
        'platelets': LeukocytesEnumToJSON(value.platelets),
        'erythrocytes': LeukocytesEnumToJSON(value.erythrocytes),
        'leukocytes': LeukocytesEnumToJSON(value.leukocytes),
        'address': value.address,
        'site': value.site,
        'phones': value.phones,
        'email': value.email,
        'worktime': value.worktime,
        'without_registration': value.withoutRegistration,
        'with_typing': value.withTyping,
        'for_moscow': value.forMoscow,
        'closed': value.closed,
        'priority': value.priority,
    };
}

