/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BloodStationPhone
 */
export interface BloodStationPhone {
    /**
     * 
     * @type {number}
     * @memberof BloodStationPhone
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof BloodStationPhone
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof BloodStationPhone
     */
    comment?: string;
}

/**
 * Check if a given object implements the BloodStationPhone interface.
 */
export function instanceOfBloodStationPhone(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "phone" in value;

    return isInstance;
}

export function BloodStationPhoneFromJSON(json: any): BloodStationPhone {
    return BloodStationPhoneFromJSONTyped(json, false);
}

export function BloodStationPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodStationPhone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'phone': json['phone'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function BloodStationPhoneToJSON(value?: BloodStationPhone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'comment': value.comment,
    };
}

