/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * * `unknown` - нет данных
 * @export
 */
export const BMinusC07Enum = {
    Need: 'need',
    NoNeed: 'no_need',
    Unknown: 'unknown'
} as const;
export type BMinusC07Enum = typeof BMinusC07Enum[keyof typeof BMinusC07Enum];


export function BMinusC07EnumFromJSON(json: any): BMinusC07Enum {
    return BMinusC07EnumFromJSONTyped(json, false);
}

export function BMinusC07EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BMinusC07Enum {
    return json as BMinusC07Enum;
}

export function BMinusC07EnumToJSON(value?: BMinusC07Enum | null): any {
    return value as any;
}

