/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const BMinusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type BMinusAf7Enum = typeof BMinusAf7Enum[keyof typeof BMinusAf7Enum];


export function BMinusAf7EnumFromJSON(json: any): BMinusAf7Enum {
    return BMinusAf7EnumFromJSONTyped(json, false);
}

export function BMinusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BMinusAf7Enum {
    return json as BMinusAf7Enum;
}

export function BMinusAf7EnumToJSON(value?: BMinusAf7Enum | null): any {
    return value as any;
}

