/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const BPlusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type BPlusAf7Enum = typeof BPlusAf7Enum[keyof typeof BPlusAf7Enum];


export function BPlusAf7EnumFromJSON(json: any): BPlusAf7Enum {
    return BPlusAf7EnumFromJSONTyped(json, false);
}

export function BPlusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BPlusAf7Enum {
    return json as BPlusAf7Enum;
}

export function BPlusAf7EnumToJSON(value?: BPlusAf7Enum | null): any {
    return value as any;
}

