/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { NullEnum } from './NullEnum';
import {
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import type { PaymentTypeEnum } from './PaymentTypeEnum';
import {
    PaymentTypeEnumFromJSON,
    PaymentTypeEnumFromJSONTyped,
    PaymentTypeEnumToJSON,
} from './PaymentTypeEnum';

/**
 * @type DonationPlanPaymentType
 * 
 * @export
 */
export type DonationPlanPaymentType = BlankEnum | NullEnum | PaymentTypeEnum;

export function DonationPlanPaymentTypeFromJSON(json: any): DonationPlanPaymentType {
    return DonationPlanPaymentTypeFromJSONTyped(json, false);
}

export function DonationPlanPaymentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationPlanPaymentType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { error: 'error' } as any;
}

export function DonationPlanPaymentTypeToJSON(value?: DonationPlanPaymentType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {};
}

