/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonationAggTop
 */
export interface DonationAggTop {
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    count?: number;
    /**
     * 
     * @type {Date}
     * @memberof DonationAggTop
     */
    lastDonationAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    blood?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    plasma?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    platelets?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    erythrocytes?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    leukocytes?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    unconfirmedDonations?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    countYear?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    bloodYear?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    plasmaYear?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    plateletsYear?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    erythrocytesYear?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAggTop
     */
    leukocytesYear?: number;
}

/**
 * Check if a given object implements the DonationAggTop interface.
 */
export function instanceOfDonationAggTop(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DonationAggTopFromJSON(json: any): DonationAggTop {
    return DonationAggTopFromJSONTyped(json, false);
}

export function DonationAggTopFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationAggTop {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'lastDonationAt': !exists(json, 'last_donation_at') ? undefined : (json['last_donation_at'] === null ? null : new Date(json['last_donation_at'])),
        'blood': !exists(json, 'blood') ? undefined : json['blood'],
        'plasma': !exists(json, 'plasma') ? undefined : json['plasma'],
        'platelets': !exists(json, 'platelets') ? undefined : json['platelets'],
        'erythrocytes': !exists(json, 'erythrocytes') ? undefined : json['erythrocytes'],
        'leukocytes': !exists(json, 'leukocytes') ? undefined : json['leukocytes'],
        'unconfirmedDonations': !exists(json, 'unconfirmed_donations') ? undefined : json['unconfirmed_donations'],
        'countYear': !exists(json, 'count_year') ? undefined : json['count_year'],
        'bloodYear': !exists(json, 'blood_year') ? undefined : json['blood_year'],
        'plasmaYear': !exists(json, 'plasma_year') ? undefined : json['plasma_year'],
        'plateletsYear': !exists(json, 'platelets_year') ? undefined : json['platelets_year'],
        'erythrocytesYear': !exists(json, 'erythrocytes_year') ? undefined : json['erythrocytes_year'],
        'leukocytesYear': !exists(json, 'leukocytes_year') ? undefined : json['leukocytes_year'],
    };
}

export function DonationAggTopToJSON(value?: DonationAggTop | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'last_donation_at': value.lastDonationAt === undefined ? undefined : (value.lastDonationAt === null ? null : value.lastDonationAt.toISOString().substring(0,10)),
        'blood': value.blood,
        'plasma': value.plasma,
        'platelets': value.platelets,
        'erythrocytes': value.erythrocytes,
        'leukocytes': value.leukocytes,
        'unconfirmed_donations': value.unconfirmedDonations,
        'count_year': value.countYear,
        'blood_year': value.bloodYear,
        'plasma_year': value.plasmaYear,
        'platelets_year': value.plateletsYear,
        'erythrocytes_year': value.erythrocytesYear,
        'leukocytes_year': value.leukocytesYear,
    };
}

