/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonationAgg
 */
export interface DonationAgg {
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    count?: number;
    /**
     * 
     * @type {Date}
     * @memberof DonationAgg
     */
    lastDonationAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    blood?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    plasma?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    platelets?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    erythrocytes?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    leukocytes?: number;
    /**
     * 
     * @type {number}
     * @memberof DonationAgg
     */
    unconfirmedDonations?: number;
}

/**
 * Check if a given object implements the DonationAgg interface.
 */
export function instanceOfDonationAgg(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DonationAggFromJSON(json: any): DonationAgg {
    return DonationAggFromJSONTyped(json, false);
}

export function DonationAggFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationAgg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'lastDonationAt': !exists(json, 'last_donation_at') ? undefined : (json['last_donation_at'] === null ? null : new Date(json['last_donation_at'])),
        'blood': !exists(json, 'blood') ? undefined : json['blood'],
        'plasma': !exists(json, 'plasma') ? undefined : json['plasma'],
        'platelets': !exists(json, 'platelets') ? undefined : json['platelets'],
        'erythrocytes': !exists(json, 'erythrocytes') ? undefined : json['erythrocytes'],
        'leukocytes': !exists(json, 'leukocytes') ? undefined : json['leukocytes'],
        'unconfirmedDonations': !exists(json, 'unconfirmed_donations') ? undefined : json['unconfirmed_donations'],
    };
}

export function DonationAggToJSON(value?: DonationAgg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'last_donation_at': value.lastDonationAt === undefined ? undefined : (value.lastDonationAt === null ? null : value.lastDonationAt.toISOString().substring(0,10)),
        'blood': value.blood,
        'plasma': value.plasma,
        'platelets': value.platelets,
        'erythrocytes': value.erythrocytes,
        'leukocytes': value.leukocytes,
        'unconfirmed_donations': value.unconfirmedDonations,
    };
}

