/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `active` - донация запланирована
 * * `abort` - планирование отменено
 * * `done` - запланированная донация добавлена
 * * `widget_abort` - отказ прикрепить справку к прошедшему планированию
 * @export
 */
export const DonationPlanStatusEnum = {
    Active: 'active',
    Abort: 'abort',
    Done: 'done',
    WidgetAbort: 'widget_abort'
} as const;
export type DonationPlanStatusEnum = typeof DonationPlanStatusEnum[keyof typeof DonationPlanStatusEnum];


export function DonationPlanStatusEnumFromJSON(json: any): DonationPlanStatusEnum {
    return DonationPlanStatusEnumFromJSONTyped(json, false);
}

export function DonationPlanStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationPlanStatusEnum {
    return json as DonationPlanStatusEnum;
}

export function DonationPlanStatusEnumToJSON(value?: DonationPlanStatusEnum | null): any {
    return value as any;
}

