/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonorStatus
 */
export interface DonorStatus {
    /**
     * 
     * @type {number}
     * @memberof DonorStatus
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof DonorStatus
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DonorStatus
     */
    donationsCount: number;
    /**
     * 
     * @type {string}
     * @memberof DonorStatus
     */
    backgroundColor?: string;
    /**
     * 
     * @type {string}
     * @memberof DonorStatus
     */
    textColor?: string;
}

/**
 * Check if a given object implements the DonorStatus interface.
 */
export function instanceOfDonorStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "donationsCount" in value;

    return isInstance;
}

export function DonorStatusFromJSON(json: any): DonorStatus {
    return DonorStatusFromJSONTyped(json, false);
}

export function DonorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonorStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'donationsCount': json['donations_count'],
        'backgroundColor': !exists(json, 'background_color') ? undefined : json['background_color'],
        'textColor': !exists(json, 'text_color') ? undefined : json['text_color'],
    };
}

export function DonorStatusToJSON(value?: DonorStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'donations_count': value.donationsCount,
        'background_color': value.backgroundColor,
        'text_color': value.textColor,
    };
}

