/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailConfirmationSerialzier
 */
export interface EmailConfirmationSerialzier {
    /**
     * 
     * @type {string}
     * @memberof EmailConfirmationSerialzier
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof EmailConfirmationSerialzier
     */
    code: number;
}

/**
 * Check if a given object implements the EmailConfirmationSerialzier interface.
 */
export function instanceOfEmailConfirmationSerialzier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function EmailConfirmationSerialzierFromJSON(json: any): EmailConfirmationSerialzier {
    return EmailConfirmationSerialzierFromJSONTyped(json, false);
}

export function EmailConfirmationSerialzierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfirmationSerialzier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function EmailConfirmationSerialzierToJSON(value?: EmailConfirmationSerialzier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'code': value.code,
    };
}

