/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailVerificationSerialzier
 */
export interface EmailVerificationSerialzier {
    /**
     * 
     * @type {number}
     * @memberof EmailVerificationSerialzier
     */
    code: number;
    /**
     * 
     * @type {number}
     * @memberof EmailVerificationSerialzier
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof EmailVerificationSerialzier
     */
    email: string;
}

/**
 * Check if a given object implements the EmailVerificationSerialzier interface.
 */
export function instanceOfEmailVerificationSerialzier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function EmailVerificationSerialzierFromJSON(json: any): EmailVerificationSerialzier {
    return EmailVerificationSerialzierFromJSONTyped(json, false);
}

export function EmailVerificationSerialzierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationSerialzier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'userId': json['user_id'],
        'email': json['email'],
    };
}

export function EmailVerificationSerialzierToJSON(value?: EmailVerificationSerialzier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'user_id': value.userId,
        'email': value.email,
    };
}

