/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailRegistration
 */
export interface EmailRegistration {
    /**
     * 
     * @type {string}
     * @memberof EmailRegistration
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegistration
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegistration
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegistration
     */
    tag?: string;
}

/**
 * Check if a given object implements the EmailRegistration interface.
 */
export function instanceOfEmailRegistration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "firstName" in value;

    return isInstance;
}

export function EmailRegistrationFromJSON(json: any): EmailRegistration {
    return EmailRegistrationFromJSONTyped(json, false);
}

export function EmailRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['first_name'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
    };
}

export function EmailRegistrationToJSON(value?: EmailRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'first_name': value.firstName,
        'tag': value.tag,
    };
}

