/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailChangeSerialzier
 */
export interface EmailChangeSerialzier {
    /**
     * 
     * @type {string}
     * @memberof EmailChangeSerialzier
     */
    email: string;
}

/**
 * Check if a given object implements the EmailChangeSerialzier interface.
 */
export function instanceOfEmailChangeSerialzier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function EmailChangeSerialzierFromJSON(json: any): EmailChangeSerialzier {
    return EmailChangeSerialzierFromJSONTyped(json, false);
}

export function EmailChangeSerialzierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailChangeSerialzier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailChangeSerialzierToJSON(value?: EmailChangeSerialzier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

