/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlinePicture
 */
export interface InlinePicture {
    /**
     * 
     * @type {string}
     * @memberof InlinePicture
     */
    readonly image: string;
}

/**
 * Check if a given object implements the InlinePicture interface.
 */
export function instanceOfInlinePicture(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function InlinePictureFromJSON(json: any): InlinePicture {
    return InlinePictureFromJSONTyped(json, false);
}

export function InlinePictureFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlinePicture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function InlinePictureToJSON(value?: InlinePicture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

