/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `positive` - Положительный
 * * `negative` - Отрицательный
 * * `dont_know` - Не знаю
 * @export
 */
export const KellEnum = {
    Positive: 'positive',
    Negative: 'negative',
    DontKnow: 'dont_know'
} as const;
export type KellEnum = typeof KellEnum[keyof typeof KellEnum];


export function KellEnumFromJSON(json: any): KellEnum {
    return KellEnumFromJSONTyped(json, false);
}

export function KellEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): KellEnum {
    return json as KellEnum;
}

export function KellEnumToJSON(value?: KellEnum | null): any {
    return value as any;
}

