/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { KellEnum } from './KellEnum';
import {
    KellEnumFromJSON,
    KellEnumFromJSONTyped,
    KellEnumToJSON,
} from './KellEnum';
import type { NullEnum } from './NullEnum';
import {
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';

/**
 * @type Kell
 * 
 * @export
 */
export type Kell = BlankEnum | KellEnum | NullEnum;

export function KellFromJSON(json: any): Kell {
    return KellFromJSONTyped(json, false);
}

export function KellFromJSONTyped(json: any, ignoreDiscriminator: boolean): Kell {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json;
}

export function KellToJSON(value?: Kell | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return {};
}

