/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * * `unknown` - нет данных
 * @export
 */
export const OMinusC07Enum = {
    Need: 'need',
    NoNeed: 'no_need',
    Unknown: 'unknown'
} as const;
export type OMinusC07Enum = typeof OMinusC07Enum[keyof typeof OMinusC07Enum];


export function OMinusC07EnumFromJSON(json: any): OMinusC07Enum {
    return OMinusC07EnumFromJSONTyped(json, false);
}

export function OMinusC07EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OMinusC07Enum {
    return json as OMinusC07Enum;
}

export function OMinusC07EnumToJSON(value?: OMinusC07Enum | null): any {
    return value as any;
}

