/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const OMinusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type OMinusAf7Enum = typeof OMinusAf7Enum[keyof typeof OMinusAf7Enum];


export function OMinusAf7EnumFromJSON(json: any): OMinusAf7Enum {
    return OMinusAf7EnumFromJSONTyped(json, false);
}

export function OMinusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OMinusAf7Enum {
    return json as OMinusAf7Enum;
}

export function OMinusAf7EnumToJSON(value?: OMinusAf7Enum | null): any {
    return value as any;
}

