/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * * `unknown` - нет данных
 * @export
 */
export const OPlusC07Enum = {
    Need: 'need',
    NoNeed: 'no_need',
    Unknown: 'unknown'
} as const;
export type OPlusC07Enum = typeof OPlusC07Enum[keyof typeof OPlusC07Enum];


export function OPlusC07EnumFromJSON(json: any): OPlusC07Enum {
    return OPlusC07EnumFromJSONTyped(json, false);
}

export function OPlusC07EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OPlusC07Enum {
    return json as OPlusC07Enum;
}

export function OPlusC07EnumToJSON(value?: OPlusC07Enum | null): any {
    return value as any;
}

