/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * @export
 */
export const OPlusAf7Enum = {
    Need: 'need',
    NoNeed: 'no_need'
} as const;
export type OPlusAf7Enum = typeof OPlusAf7Enum[keyof typeof OPlusAf7Enum];


export function OPlusAf7EnumFromJSON(json: any): OPlusAf7Enum {
    return OPlusAf7EnumFromJSONTyped(json, false);
}

export function OPlusAf7EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OPlusAf7Enum {
    return json as OPlusAf7Enum;
}

export function OPlusAf7EnumToJSON(value?: OPlusAf7Enum | null): any {
    return value as any;
}

