/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DonationPlan } from './DonationPlan';
import {
    DonationPlanFromJSON,
    DonationPlanFromJSONTyped,
    DonationPlanToJSON,
} from './DonationPlan';

/**
 * 
 * @export
 * @interface PaginatedDonationPlanList
 */
export interface PaginatedDonationPlanList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDonationPlanList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDonationPlanList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDonationPlanList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<DonationPlan>}
     * @memberof PaginatedDonationPlanList
     */
    results?: Array<DonationPlan>;
}

/**
 * Check if a given object implements the PaginatedDonationPlanList interface.
 */
export function instanceOfPaginatedDonationPlanList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedDonationPlanListFromJSON(json: any): PaginatedDonationPlanList {
    return PaginatedDonationPlanListFromJSONTyped(json, false);
}

export function PaginatedDonationPlanListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDonationPlanList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DonationPlanFromJSON)),
    };
}

export function PaginatedDonationPlanListToJSON(value?: PaginatedDonationPlanList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DonationPlanToJSON)),
    };
}

