/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BloodStationWithNeeds } from './BloodStationWithNeeds';
import {
    BloodStationWithNeedsFromJSON,
    BloodStationWithNeedsFromJSONTyped,
    BloodStationWithNeedsToJSON,
} from './BloodStationWithNeeds';

/**
 * 
 * @export
 * @interface PaginatedBloodStationWithNeedsList
 */
export interface PaginatedBloodStationWithNeedsList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBloodStationWithNeedsList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBloodStationWithNeedsList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBloodStationWithNeedsList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BloodStationWithNeeds>}
     * @memberof PaginatedBloodStationWithNeedsList
     */
    results?: Array<BloodStationWithNeeds>;
}

/**
 * Check if a given object implements the PaginatedBloodStationWithNeedsList interface.
 */
export function instanceOfPaginatedBloodStationWithNeedsList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBloodStationWithNeedsListFromJSON(json: any): PaginatedBloodStationWithNeedsList {
    return PaginatedBloodStationWithNeedsListFromJSONTyped(json, false);
}

export function PaginatedBloodStationWithNeedsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBloodStationWithNeedsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(BloodStationWithNeedsFromJSON)),
    };
}

export function PaginatedBloodStationWithNeedsListToJSON(value?: PaginatedBloodStationWithNeedsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(BloodStationWithNeedsToJSON)),
    };
}

