/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
} from './City';

/**
 * 
 * @export
 * @interface PaginatedCityList
 */
export interface PaginatedCityList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCityList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCityList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCityList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<City>}
     * @memberof PaginatedCityList
     */
    results?: Array<City>;
}

/**
 * Check if a given object implements the PaginatedCityList interface.
 */
export function instanceOfPaginatedCityList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedCityListFromJSON(json: any): PaginatedCityList {
    return PaginatedCityListFromJSONTyped(json, false);
}

export function PaginatedCityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCityList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CityFromJSON)),
    };
}

export function PaginatedCityListToJSON(value?: PaginatedCityList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CityToJSON)),
    };
}

