/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Donation } from './Donation';
import {
    DonationFromJSON,
    DonationFromJSONTyped,
    DonationToJSON,
} from './Donation';

/**
 * 
 * @export
 * @interface PaginatedDonationList
 */
export interface PaginatedDonationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDonationList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDonationList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDonationList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Donation>}
     * @memberof PaginatedDonationList
     */
    results?: Array<Donation>;
}

/**
 * Check if a given object implements the PaginatedDonationList interface.
 */
export function instanceOfPaginatedDonationList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedDonationListFromJSON(json: any): PaginatedDonationList {
    return PaginatedDonationListFromJSONTyped(json, false);
}

export function PaginatedDonationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDonationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DonationFromJSON)),
    };
}

export function PaginatedDonationListToJSON(value?: PaginatedDonationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DonationToJSON)),
    };
}

