/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BonusList } from './BonusList';
import {
    BonusListFromJSON,
    BonusListFromJSONTyped,
    BonusListToJSON,
} from './BonusList';

/**
 * 
 * @export
 * @interface PaginatedBonusListList
 */
export interface PaginatedBonusListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBonusListList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBonusListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBonusListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BonusList>}
     * @memberof PaginatedBonusListList
     */
    results?: Array<BonusList>;
}

/**
 * Check if a given object implements the PaginatedBonusListList interface.
 */
export function instanceOfPaginatedBonusListList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBonusListListFromJSON(json: any): PaginatedBonusListList {
    return PaginatedBonusListListFromJSONTyped(json, false);
}

export function PaginatedBonusListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBonusListList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(BonusListFromJSON)),
    };
}

export function PaginatedBonusListListToJSON(value?: PaginatedBonusListList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(BonusListToJSON)),
    };
}

