/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NullEnum } from './NullEnum';
import {
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import type { RejectReasonEnum } from './RejectReasonEnum';
import {
    RejectReasonEnumFromJSON,
    RejectReasonEnumFromJSONTyped,
    RejectReasonEnumToJSON,
} from './RejectReasonEnum';

/**
 * @type PatchedDonationRejectReason
 * 
 * @export
 */
export type PatchedDonationRejectReason = NullEnum | RejectReasonEnum;

export function PatchedDonationRejectReasonFromJSON(json: any): PatchedDonationRejectReason {
    return PatchedDonationRejectReasonFromJSONTyped(json, false);
}

export function PatchedDonationRejectReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDonationRejectReason {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json
}

export function PatchedDonationRejectReasonToJSON(value?: PatchedDonationRejectReason | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return value
}

