/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { NullEnum } from './NullEnum';
import {
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import type { PaymentTypeEnum } from './PaymentTypeEnum';
import {
    PaymentTypeEnumFromJSON,
    PaymentTypeEnumFromJSONTyped,
    PaymentTypeEnumToJSON,
} from './PaymentTypeEnum';

/**
 * @type PatchedDonationPlanPaymentType
 * 
 * @export
 */
export type PatchedDonationPlanPaymentType = BlankEnum | NullEnum | PaymentTypeEnum;

export function PatchedDonationPlanPaymentTypeFromJSON(json: any): PatchedDonationPlanPaymentType {
    return PatchedDonationPlanPaymentTypeFromJSONTyped(json, false);
}

export function PatchedDonationPlanPaymentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDonationPlanPaymentType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json;
}

export function PatchedDonationPlanPaymentTypeToJSON(value?: PatchedDonationPlanPaymentType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return value
}

