/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
} from './City';
import type { DonationAgg } from './DonationAgg';
import {
    DonationAggFromJSON,
    DonationAggFromJSONTyped,
    DonationAggToJSON,
} from './DonationAgg';
import type { DonorStatus } from './DonorStatus';
import {
    DonorStatusFromJSON,
    DonorStatusFromJSONTyped,
    DonorStatusToJSON,
} from './DonorStatus';
import type { InlinePicture } from './InlinePicture';
import {
    InlinePictureFromJSON,
    InlinePictureFromJSONTyped,
    InlinePictureToJSON,
} from './InlinePicture';
import type { PatchedUserGender } from './PatchedUserGender';
import {
    PatchedUserGenderFromJSON,
    PatchedUserGenderFromJSONTyped,
    PatchedUserGenderToJSON,
} from './PatchedUserGender';
import type { SimpleUserSocialAuth } from './SimpleUserSocialAuth';
import {
    SimpleUserSocialAuthFromJSON,
    SimpleUserSocialAuthFromJSONTyped,
    SimpleUserSocialAuthToJSON,
} from './SimpleUserSocialAuth';
import type { TopUsers } from './TopUsers';
import {
    TopUsersFromJSON,
    TopUsersFromJSONTyped,
    TopUsersToJSON,
} from './TopUsers';

/**
 * 
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    readonly dateJoined?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    maidenName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {PatchedUserGender}
     * @memberof PatchedUser
     */
    gender?: PatchedUserGender;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    loginViaPhone?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    about?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    cityId?: number;
    /**
     * 
     * @type {City}
     * @memberof PatchedUser
     */
    readonly city?: City;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    isPin20?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    isPin100?: boolean;
    /**
     * 
     * @type {DonationAgg}
     * @memberof PatchedUser
     */
    readonly donationAgg?: DonationAgg;
    /**
     * 
     * @type {Array<SimpleUserSocialAuth>}
     * @memberof PatchedUser
     */
    readonly socials?: Array<SimpleUserSocialAuth>;
    /**
     * 
     * @type {InlinePicture}
     * @memberof PatchedUser
     */
    readonly photo?: InlinePicture;
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    photoId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly nextDonationDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly nextDonation?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly bloodGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly hasPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly isEmailVerified?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly isPhoneVerified?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    emailReconfirmedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    phoneReconfirmedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly legacyAvatar?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly startDonorYear?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly referalCode?: string;
    /**
     * 
     * @type {TopUsers}
     * @memberof PatchedUser
     */
    readonly parentUser?: TopUsers;
    /**
     * 
     * @type {Array<TopUsers>}
     * @memberof PatchedUser
     */
    readonly invitedUsers?: Array<TopUsers>;
    /**
     * 
     * @type {DonorStatus}
     * @memberof PatchedUser
     */
    readonly donorStatus?: DonorStatus;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly managedOrganizations?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly joinedEvents?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly joinedOrganizations?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    donorCertificate?: boolean;
}

/**
 * Check if a given object implements the PatchedUser interface.
 */
export function instanceOfPatchedUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
    return PatchedUserFromJSONTyped(json, false);
}

export function PatchedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'dateJoined': !exists(json, 'date_joined') ? undefined : (new Date(json['date_joined'])),
        'username': !exists(json, 'username') ? undefined : json['username'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'maidenName': !exists(json, 'maiden_name') ? undefined : json['maiden_name'],
        'birthDate': !exists(json, 'birth_date') ? undefined : (json['birth_date'] === null ? null : new Date(json['birth_date'])),
        'gender': !exists(json, 'gender') ? undefined : PatchedUserGenderFromJSON(json['gender']),
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'loginViaPhone': !exists(json, 'login_via_phone') ? undefined : json['login_via_phone'],
        'about': !exists(json, 'about') ? undefined : json['about'],
        'cityId': !exists(json, 'city_id') ? undefined : json['city_id'],
        'city': !exists(json, 'city') ? undefined : CityFromJSON(json['city']),
        'isPin20': !exists(json, 'is_pin_20') ? undefined : json['is_pin_20'],
        'isPin100': !exists(json, 'is_pin_100') ? undefined : json['is_pin_100'],
        'donationAgg': !exists(json, 'donation_agg') ? undefined : DonationAggFromJSON(json['donation_agg']),
        'socials': !exists(json, 'socials') ? undefined : ((json['socials'] as Array<any>).map(SimpleUserSocialAuthFromJSON)),
        'photo': !exists(json, 'photo') ? undefined : InlinePictureFromJSON(json['photo']),
        'photoId': !exists(json, 'photo_id') ? undefined : json['photo_id'],
        'nextDonationDate': !exists(json, 'next_donation_date') ? undefined : json['next_donation_date'],
        'nextDonation': !exists(json, 'next_donation') ? undefined : json['next_donation'],
        'bloodGroup': !exists(json, 'blood_group') ? undefined : json['blood_group'],
        'hasPassword': !exists(json, 'has_password') ? undefined : json['has_password'],
        'isEmailVerified': !exists(json, 'is_email_verified') ? undefined : json['is_email_verified'],
        'isPhoneVerified': !exists(json, 'is_phone_verified') ? undefined : json['is_phone_verified'],
        'emailReconfirmedAt': !exists(json, 'email_reconfirmed_at') ? undefined : (json['email_reconfirmed_at'] === null ? null : new Date(json['email_reconfirmed_at'])),
        'phoneReconfirmedAt': !exists(json, 'phone_reconfirmed_at') ? undefined : (json['phone_reconfirmed_at'] === null ? null : new Date(json['phone_reconfirmed_at'])),
        'legacyAvatar': !exists(json, 'legacy_avatar') ? undefined : json['legacy_avatar'],
        'startDonorYear': !exists(json, 'start_donor_year') ? undefined : json['start_donor_year'],
        'referalCode': !exists(json, 'referal_code') ? undefined : json['referal_code'],
        'parentUser': !exists(json, 'parent_user') ? undefined : TopUsersFromJSON(json['parent_user']),
        'invitedUsers': !exists(json, 'invited_users') ? undefined : ((json['invited_users'] as Array<any>).map(TopUsersFromJSON)),
        'donorStatus': !exists(json, 'donor_status') ? undefined : DonorStatusFromJSON(json['donor_status']),
        'managedOrganizations': !exists(json, 'managed_organizations') ? undefined : json['managed_organizations'],
        'joinedEvents': !exists(json, 'joined_events') ? undefined : json['joined_events'],
        'joinedOrganizations': !exists(json, 'joined_organizations') ? undefined : json['joined_organizations'],
        'donorCertificate': !exists(json, 'donor_certificate') ? undefined : json['donor_certificate'],
    };
}

export function PatchedUserToJSON(value?: PatchedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'middle_name': value.middleName,
        'maiden_name': value.maidenName,
        'birth_date': value.birthDate === undefined ? undefined : (value.birthDate === null ? null : value.birthDate.toISOString().substring(0,10)),
        'gender': PatchedUserGenderToJSON(value.gender),
        'login_via_phone': value.loginViaPhone,
        'about': value.about,
        'city_id': value.cityId,
        'is_pin_20': value.isPin20,
        'is_pin_100': value.isPin100,
        'photo_id': value.photoId,
        'email_reconfirmed_at': value.emailReconfirmedAt === undefined ? undefined : (value.emailReconfirmedAt === null ? null : value.emailReconfirmedAt.toISOString()),
        'phone_reconfirmed_at': value.phoneReconfirmedAt === undefined ? undefined : (value.phoneReconfirmedAt === null ? null : value.phoneReconfirmedAt.toISOString()),
        'donor_certificate': value.donorCertificate,
    };
}

