/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Kell } from './Kell';
import {
    KellFromJSON,
    KellFromJSONTyped,
    KellToJSON,
} from './Kell';
import type { PatchedDonorCardBloodGroup } from './PatchedDonorCardBloodGroup';
import {
    PatchedDonorCardBloodGroupFromJSON,
    PatchedDonorCardBloodGroupFromJSONTyped,
    PatchedDonorCardBloodGroupToJSON,
} from './PatchedDonorCardBloodGroup';

/**
 * 
 * @export
 * @interface PatchedDonorCard
 */
export interface PatchedDonorCard {
    /**
     * 
     * @type {PatchedDonorCardBloodGroup}
     * @memberof PatchedDonorCard
     */
    bloodGroup?: PatchedDonorCardBloodGroup | null;
    /**
     * 
     * @type {Kell}
     * @memberof PatchedDonorCard
     */
    kell?: Kell | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    blood?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    plasma?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    platelets?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    erythrocytes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    leukocytes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonateDisqualification?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonateSurgery?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonateLactation?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonateOther?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    cantDonateDonor?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDonorCard
     */
    cantDonateNotice?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedDonorCard
     */
    boneDonor?: boolean;
    /**
     * число донаций пользователя до регистрации на DonorSearch
     * @type {number}
     * @memberof PatchedDonorCard
     */
    donationsBeforeReg?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedDonorCard
     */
    donorStatus?: number;
}

/**
 * Check if a given object implements the PatchedDonorCard interface.
 */
export function instanceOfPatchedDonorCard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedDonorCardFromJSON(json: any): PatchedDonorCard {
    return PatchedDonorCardFromJSONTyped(json, false);
}

export function PatchedDonorCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDonorCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bloodGroup': !exists(json, 'blood_group') ? undefined : PatchedDonorCardBloodGroupFromJSON(json['blood_group']),
        'kell': !exists(json, 'kell') ? undefined : KellFromJSON(json['kell']),
        'blood': !exists(json, 'blood') ? undefined : json['blood'],
        'plasma': !exists(json, 'plasma') ? undefined : json['plasma'],
        'platelets': !exists(json, 'platelets') ? undefined : json['platelets'],
        'erythrocytes': !exists(json, 'erythrocytes') ? undefined : json['erythrocytes'],
        'leukocytes': !exists(json, 'leukocytes') ? undefined : json['leukocytes'],
        'cantDonate': !exists(json, 'cant_donate') ? undefined : json['cant_donate'],
        'cantDonateDisqualification': !exists(json, 'cant_donate_disqualification') ? undefined : json['cant_donate_disqualification'],
        'cantDonateSurgery': !exists(json, 'cant_donate_surgery') ? undefined : json['cant_donate_surgery'],
        'cantDonateLactation': !exists(json, 'cant_donate_lactation') ? undefined : json['cant_donate_lactation'],
        'cantDonateOther': !exists(json, 'cant_donate_other') ? undefined : json['cant_donate_other'],
        'cantDonateDonor': !exists(json, 'cant_donate_donor') ? undefined : json['cant_donate_donor'],
        'cantDonateNotice': !exists(json, 'cant_donate_notice') ? undefined : (json['cant_donate_notice'] === null ? null : new Date(json['cant_donate_notice'])),
        'boneDonor': !exists(json, 'bone_donor') ? undefined : json['bone_donor'],
        'donationsBeforeReg': !exists(json, 'donations_before_reg') ? undefined : json['donations_before_reg'],
        'donorStatus': !exists(json, 'donor_status') ? undefined : json['donor_status'],
    };
}

export function PatchedDonorCardToJSON(value?: PatchedDonorCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blood_group': PatchedDonorCardBloodGroupToJSON(value.bloodGroup),
        'kell': KellToJSON(value.kell),
        'blood': value.blood,
        'plasma': value.plasma,
        'platelets': value.platelets,
        'erythrocytes': value.erythrocytes,
        'leukocytes': value.leukocytes,
        'cant_donate': value.cantDonate,
        'cant_donate_disqualification': value.cantDonateDisqualification,
        'cant_donate_surgery': value.cantDonateSurgery,
        'cant_donate_lactation': value.cantDonateLactation,
        'cant_donate_other': value.cantDonateOther,
        'cant_donate_donor': value.cantDonateDonor,
        'cant_donate_notice': value.cantDonateNotice === undefined ? undefined : (value.cantDonateNotice === null ? null : value.cantDonateNotice.toISOString().substring(0,10)),
        'bone_donor': value.boneDonor,
        'donations_before_reg': value.donationsBeforeReg,
        'donor_status': value.donorStatus,
    };
}

