/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { GenderEnum } from './GenderEnum';
import {
    GenderEnumFromJSON,
    GenderEnumFromJSONTyped,
    GenderEnumToJSON,
} from './GenderEnum';

/**
 * @type PatchedUserGender
 * 
 * @export
 */
export type PatchedUserGender = BlankEnum | GenderEnum;

export function PatchedUserGenderFromJSON(json: any): PatchedUserGender {
    return PatchedUserGenderFromJSONTyped(json, false);
}

export function PatchedUserGenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserGender {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json
}

export function PatchedUserGenderToJSON(value?: PatchedUserGender | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    return value
}

