/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `free` - Безвозмездно
 * * `payed` - Платно
 * @export
 */
export const PaymentTypeEnum = {
    Free: 'free',
    Payed: 'payed'
} as const;
export type PaymentTypeEnum = typeof PaymentTypeEnum[keyof typeof PaymentTypeEnum];


export function PaymentTypeEnumFromJSON(json: any): PaymentTypeEnum {
    return PaymentTypeEnumFromJSONTyped(json, false);
}

export function PaymentTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentTypeEnum {
    return json as PaymentTypeEnum;
}

export function PaymentTypeEnumToJSON(value?: PaymentTypeEnum | null): any {
    return value as any;
}

