/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneVerificationSerialzier
 */
export interface PhoneVerificationSerialzier {
    /**
     * 
     * @type {number}
     * @memberof PhoneVerificationSerialzier
     */
    code: number;
    /**
     * 
     * @type {number}
     * @memberof PhoneVerificationSerialzier
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof PhoneVerificationSerialzier
     */
    phone: string;
}

/**
 * Check if a given object implements the PhoneVerificationSerialzier interface.
 */
export function instanceOfPhoneVerificationSerialzier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "phone" in value;

    return isInstance;
}

export function PhoneVerificationSerialzierFromJSON(json: any): PhoneVerificationSerialzier {
    return PhoneVerificationSerialzierFromJSONTyped(json, false);
}

export function PhoneVerificationSerialzierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneVerificationSerialzier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'userId': json['user_id'],
        'phone': json['phone'],
    };
}

export function PhoneVerificationSerialzierToJSON(value?: PhoneVerificationSerialzier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'user_id': value.userId,
        'phone': value.phone,
    };
}

