/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneConfirmationSerialzier
 */
export interface PhoneConfirmationSerialzier {
    /**
     * 
     * @type {string}
     * @memberof PhoneConfirmationSerialzier
     */
    phone: string;
    /**
     * 
     * @type {number}
     * @memberof PhoneConfirmationSerialzier
     */
    code: number;
}

/**
 * Check if a given object implements the PhoneConfirmationSerialzier interface.
 */
export function instanceOfPhoneConfirmationSerialzier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "phone" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function PhoneConfirmationSerialzierFromJSON(json: any): PhoneConfirmationSerialzier {
    return PhoneConfirmationSerialzierFromJSONTyped(json, false);
}

export function PhoneConfirmationSerialzierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneConfirmationSerialzier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'code': json['code'],
    };
}

export function PhoneConfirmationSerialzierToJSON(value?: PhoneConfirmationSerialzier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'code': value.code,
    };
}

