/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Picture
 */
export interface Picture {
    /**
     * 
     * @type {number}
     * @memberof Picture
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Picture
     */
    image: string;
    /**
     * 
     * @type {Date}
     * @memberof Picture
     */
    readonly dateAdded: Date;
}

/**
 * Check if a given object implements the Picture interface.
 */
export function instanceOfPicture(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "dateAdded" in value;

    return isInstance;
}

export function PictureFromJSON(json: any): Picture {
    return PictureFromJSONTyped(json, false);
}

export function PictureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Picture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
        'dateAdded': (new Date(json['date_added'])),
    };
}

export function PictureToJSON(value?: Picture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
    };
}

