/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `need` - нужна
 * * `no_need` - не нужна
 * * `unknown` - нет данных
 * @export
 */
export const PlusMinusUniversalEnum = {
    Need: 'need',
    NoNeed: 'no_need',
    Unknown: 'unknown'
} as const;
export type PlusMinusUniversalEnum = typeof PlusMinusUniversalEnum[keyof typeof PlusMinusUniversalEnum];


export function PlusMinusUniversalEnumFromJSON(json: any): PlusMinusUniversalEnum {
    return PlusMinusUniversalEnumFromJSONTyped(json, false);
}

export function PlusMinusUniversalEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlusMinusUniversalEnum {
    return json as PlusMinusUniversalEnum;
}

export function PlusMinusUniversalEnumToJSON(value?: PlusMinusUniversalEnum | null): any {
    return value as any;
}

