/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `facebook` - Facebook
 * * `vkontakte` - VK
 * * `twitter` - Twitter
 * * `odnoklassniki` - Odnoklassniki
 * * `google` - Google
 * * `yandex` - Yandex
 * * `apple` - Apple
 * @export
 */
export const ProviderEnum = {
    Facebook: 'facebook',
    Vkontakte: 'vkontakte',
    Twitter: 'twitter',
    Odnoklassniki: 'odnoklassniki',
    Google: 'google',
    Yandex: 'yandex',
    Apple: 'apple'
} as const;
export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];


export function ProviderEnumFromJSON(json: any): ProviderEnum {
    return ProviderEnumFromJSONTyped(json, false);
}

export function ProviderEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEnum {
    return json as ProviderEnum;
}

export function ProviderEnumToJSON(value?: ProviderEnum | null): any {
    return value as any;
}

