/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EmailRegistration } from './EmailRegistration';
import {
    instanceOfEmailRegistration,
    EmailRegistrationFromJSON,
    EmailRegistrationFromJSONTyped,
    EmailRegistrationToJSON,
} from './EmailRegistration';
import type { PhoneRegistration } from './PhoneRegistration';
import {
    instanceOfPhoneRegistration,
    PhoneRegistrationFromJSON,
    PhoneRegistrationFromJSONTyped,
    PhoneRegistrationToJSON,
} from './PhoneRegistration';

/**
 * @type Registration
 * 
 * @export
 */
export type Registration = EmailRegistration | PhoneRegistration;

export function RegistrationFromJSON(json: any): Registration {
    return RegistrationFromJSONTyped(json, false);
}

export function RegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Registration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...EmailRegistrationFromJSONTyped(json, true), ...PhoneRegistrationFromJSONTyped(json, true) };
}

export function RegistrationToJSON(value?: Registration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfEmailRegistration(value)) {
        return EmailRegistrationToJSON(value as EmailRegistration);
    }
    if (instanceOfPhoneRegistration(value)) {
        return PhoneRegistrationToJSON(value as PhoneRegistration);
    }

    return {};
}

