/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterNewUser200Response
 */
export interface RegisterNewUser200Response {
    /**
     * 
     * @type {string}
     * @memberof RegisterNewUser200Response
     */
    userId?: string;
}

/**
 * Check if a given object implements the RegisterNewUser200Response interface.
 */
export function instanceOfRegisterNewUser200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RegisterNewUser200ResponseFromJSON(json: any): RegisterNewUser200Response {
    return RegisterNewUser200ResponseFromJSONTyped(json, false);
}

export function RegisterNewUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNewUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function RegisterNewUser200ResponseToJSON(value?: RegisterNewUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
    };
}

