/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProviderEnum } from './ProviderEnum';
import {
    ProviderEnumFromJSON,
    ProviderEnumFromJSONTyped,
    ProviderEnumToJSON,
} from './ProviderEnum';

/**
 * 
 * @export
 * @interface SimpleUserSocialAuth
 */
export interface SimpleUserSocialAuth {
    /**
     * 
     * @type {number}
     * @memberof SimpleUserSocialAuth
     */
    readonly id: number;
    /**
     * 
     * @type {ProviderEnum}
     * @memberof SimpleUserSocialAuth
     */
    readonly provider: ProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserSocialAuth
     */
    readonly uid: string;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleUserSocialAuth
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserSocialAuth
     */
    readonly email: string | null;
}

/**
 * Check if a given object implements the SimpleUserSocialAuth interface.
 */
export function instanceOfSimpleUserSocialAuth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "provider" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function SimpleUserSocialAuthFromJSON(json: any): SimpleUserSocialAuth {
    return SimpleUserSocialAuthFromJSONTyped(json, false);
}

export function SimpleUserSocialAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUserSocialAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': ProviderEnumFromJSON(json['provider']),
        'uid': json['uid'],
        'isPublic': !exists(json, 'is_public') ? undefined : json['is_public'],
        'email': json['email'],
    };
}

export function SimpleUserSocialAuthToJSON(value?: SimpleUserSocialAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_public': value.isPublic,
    };
}

