/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `donors_found` - Доноры найдены
 * * `search_completed` - Поиск завершен
 * * `search_in_progress` - Поиск доноров продолжается
 * * `on_moderation` - На модерации
 * * `rejected` - Отклонена
 * @export
 */
export const Status2e6Enum = {
    DonorsFound: 'donors_found',
    SearchCompleted: 'search_completed',
    SearchInProgress: 'search_in_progress',
    OnModeration: 'on_moderation',
    Rejected: 'rejected'
} as const;
export type Status2e6Enum = typeof Status2e6Enum[keyof typeof Status2e6Enum];


export function Status2e6EnumFromJSON(json: any): Status2e6Enum {
    return Status2e6EnumFromJSONTyped(json, false);
}

export function Status2e6EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status2e6Enum {
    return json as Status2e6Enum;
}

export function Status2e6EnumToJSON(value?: Status2e6Enum | null): any {
    return value as any;
}

