/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `waiting` - На модерации
 * * `waiting_after_accept` - На модерации после принятия
 * * `without_image` - Без справки
 * * `accepted` - Принята
 * * `rejected` - Отклонена
 * * `deleted` - Удалена
 * @export
 */
export const Status73fEnum = {
    Waiting: 'waiting',
    WaitingAfterAccept: 'waiting_after_accept',
    WithoutImage: 'without_image',
    Accepted: 'accepted',
    Rejected: 'rejected',
    Deleted: 'deleted'
} as const;
export type Status73fEnum = typeof Status73fEnum[keyof typeof Status73fEnum];


export function Status73fEnumFromJSON(json: any): Status73fEnum {
    return Status73fEnumFromJSONTyped(json, false);
}

export function Status73fEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status73fEnum {
    return json as Status73fEnum;
}

export function Status73fEnumToJSON(value?: Status73fEnum | null): any {
    return value as any;
}

