/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserHandler
 */
export interface UserHandler {
    /**
     * 
     * @type {string}
     * @memberof UserHandler
     */
    token?: string;
    /**
     * 
     * @type {User}
     * @memberof UserHandler
     */
    user?: User;
}

/**
 * Check if a given object implements the UserHandler interface.
 */
export function instanceOfUserHandler(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserHandlerFromJSON(json: any): UserHandler {
    return UserHandlerFromJSONTyped(json, false);
}

export function UserHandlerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserHandler {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function UserHandlerToJSON(value?: UserHandler | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': UserToJSON(value.user),
    };
}

