/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { GenderEnum } from './GenderEnum';
import {
    GenderEnumFromJSON,
    GenderEnumFromJSONTyped,
    GenderEnumToJSON,
} from './GenderEnum';

/**
 * @type UserGender
 * 
 * @export
 */
export type UserGender = BlankEnum | GenderEnum;

export function UserGenderFromJSON(json: any): UserGender {
    return UserGenderFromJSONTyped(json, false);
}

export function UserGenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGender {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { 'error': 'error' } as any;
}

export function UserGenderToJSON(value?: UserGender | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {};
}

