/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PhoneVerificationSerialzier,
  User,
} from '../models/index';
import {
    PhoneVerificationSerialzierFromJSON,
    PhoneVerificationSerialzierToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface AuthConfirmPhoneRegCreateRequest {
    phoneVerificationSerialzier: PhoneVerificationSerialzier;
}

/**
 * 
 */
export class AccountCreationAndConfirmationApi extends runtime.BaseAPI {

    /**
     * Confirms phone number registration and completes the user registration process.
     * Confirm Phone Registration
     */
    async authConfirmPhoneRegCreateRaw(requestParameters: AuthConfirmPhoneRegCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters.phoneVerificationSerialzier === null || requestParameters.phoneVerificationSerialzier === undefined) {
            throw new runtime.RequiredError('phoneVerificationSerialzier','Required parameter requestParameters.phoneVerificationSerialzier was null or undefined when calling authConfirmPhoneRegCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/confirm_phone_reg/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PhoneVerificationSerialzierToJSON(requestParameters.phoneVerificationSerialzier),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Confirms phone number registration and completes the user registration process.
     * Confirm Phone Registration
     */
    async authConfirmPhoneRegCreate(requestParameters: AuthConfirmPhoneRegCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.authConfirmPhoneRegCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
