/* tslint:disable */
/* eslint-disable */
/**
 * TelegramWebDonorSearch API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedCityList,
} from '../models/index';
import {
    PaginatedCityListFromJSON,
    PaginatedCityListToJSON,
} from '../models/index';

export interface CitiesListRequest {
    allBs?: boolean;
    country?: number;
    ordering?: string;
    page?: number;
    pageSize?: number;
    region?: number;
    s?: string;
    search?: string;
    withBs?: boolean;
}

/**
 * 
 */
export class RegionsApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of cities within specified CIS countries. Supports optional search and filtering.
     * List Cities
     */
    async citiesListRaw(requestParameters: CitiesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedCityList>> {
        const queryParameters: any = {};

        if (requestParameters.allBs !== undefined) {
            queryParameters['all_bs'] = requestParameters.allBs;
        }

        if (requestParameters.country !== undefined) {
            queryParameters['country'] = requestParameters.country;
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['page_size'] = requestParameters.pageSize;
        }

        if (requestParameters.region !== undefined) {
            queryParameters['region'] = requestParameters.region;
        }

        if (requestParameters.s !== undefined) {
            queryParameters['s'] = requestParameters.s;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.withBs !== undefined) {
            queryParameters['with_bs'] = requestParameters.withBs;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/cities`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedCityListFromJSON(jsonValue));
    }

    /**
     * Retrieves a list of cities within specified CIS countries. Supports optional search and filtering.
     * List Cities
     */
    async citiesList(requestParameters: CitiesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedCityList> {
        const response = await this.citiesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
